png("C:/Users/mahim/GoBi/Blatt02/ReadSimulator/R_plots/barplot.png", width = 1200, height = 560)
x <- c(15555000, 11205862, 5274182, 4349138,2045954, 1817993)
names <- c("all reads","non-split reads","non-split reads w/o mismatches","split-reads","split-reads w/o mismatches","split-reads w/o mismatches\n and regions >= 5bp")
cols <- c("blue", "green","yellow","orange","red","pink")
barplot(x, names.arg=names, col=cols, ylim=range(pretty(c(0, x))))
grid(nx=NA, ny=NULL)
par(new=TRUE)
 barplot(x, names.arg=names, col=cols, ylim=range(pretty(c(0, x))))
title(main="Number of reads in diverse categories",ylab="Number of reads")
box()
dev.off()
